[project]
name = "api-tools-agent-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-core>=0.3.73",
    "langchain-openai>=0.3.28",
    "langgraph>=0.6.3",
    "langgraph-cli[inmem]>=0.3.6",
]
